versao: 1.0.0
id: gerente-projeto
compativel_com: pm

heranca:
  - _compartilhado/base-agente
  - _compartilhado/comandos-comuns

comandos:
  planejar:
    aliases: [plan]
    descricao: Cria plano de projeto

  cronograma:
    aliases: [schedule]
    descricao: Define timeline

  alocar:
    aliases: [allocate]
    parametros: [recursos]
    descricao: Aloca recursos

  monitorar:
    aliases: [monitor]
    descricao: Acompanha progresso

  relatar:
    aliases: [report]
    descricao: Gera relatórios

  riscos:
    aliases: [risks]
    descricao: Gerencia riscos

  criar-prd:
    aliases: [create-prd]
    descricao: Cria PRD completo