# Mapeamento BMAD → PRISMA
# Este arquivo é o coração da compatibilidade entre sistemas
# Mantém tradução bidirecional de todos comandos e agentes

versao: 1.0.0
idioma_origem: en
idioma_destino: pt-BR
ultima_atualizacao: 2025-09-16

# ===================================
# MAPEAMENTO DE AGENTES
# ===================================
agentes:
  # Mapeamento direto 1:1
  mapeamento_direto:
    bmad-orchestrator: orquestrador
    bmad-master: mestre-prisma
    analyst: analista
    architect: arquiteto
    dev: desenvolvedor
    pm: gerente-projeto
    po: product-owner
    qa: qualidade
    sm: scrum-master
    ux-expert: especialista-ux

  # Aliases aceitos (flexibilidade)
  aliases:
    # Variações do desenvolvedor
    developer: desenvolvedor
    coder: desenvolvedor
    programmer: desenvolvedor

    # Variações do PM
    project-manager: gerente-projeto
    gerente: gerente-projeto

    # Variações do PO
    product: product-owner
    dono-produto: product-owner

    # Variações do QA
    quality: qualidade
    tester: qualidade
    teste: qualidade

    # Variações do SM
    scrum: scrum-master
    agile: scrum-master

    # Variações do UX
    ux: especialista-ux
    design: especialista-ux
    ui: especialista-ux

# ===================================
# MAPEAMENTO DE COMANDOS
# ===================================
comandos:
  # Comandos básicos do sistema
  basicos:
    help: ajuda
    status: estado
    exit: sair
    quit: sair
    list: listar
    show: mostrar
    version: versao
    clear: limpar
    reset: resetar

  # Ações principais
  acoes:
    agent: agente
    task: tarefa
    workflow: fluxo
    template: modelo
    checklist: lista-verificacao
    doc: documento
    doc-out: exportar-doc
    shard: fragmentar

  # Modos especiais
  modos:
    chat-mode: modo-chat
    kb-mode: modo-kb
    party-mode: modo-festa
    yolo: modo-yolo
    debug: depuracao
    verbose: detalhado

  # Parâmetros de ação
  parametros:
    create: criar
    update: atualizar
    delete: deletar
    remove: remover
    add: adicionar
    edit: editar
    save: salvar
    load: carregar
    run: executar
    start: iniciar
    stop: parar
    restart: reiniciar

  # Comandos de desenvolvimento
  desenvolvimento:
    implement: implementar
    generate: gerar
    fix: corrigir
    refactor: refatorar
    test: testar
    analyze: analisar
    optimize: otimizar
    build: construir
    compile: compilar
    deploy: implantar
    debug: depurar

  # Comandos de análise
  analise:
    analyze: analisar
    review: revisar
    validate: validar
    check: verificar
    audit: auditar
    inspect: inspecionar
    evaluate: avaliar

# ===================================
# MAPEAMENTO DE WORKFLOWS
# ===================================
workflows:
  # Tipos principais
  tipos:
    greenfield: nascente
    brownfield: existente
    hybrid: hibrido

  # Sufixos de especialização
  sufixos:
    -fullstack: -completo
    -service: -servico
    -ui: -interface
    -api: -api
    -mobile: -movel
    -web: -web

  # Workflows completos
  completos:
    greenfield-fullstack: nascente-completo
    greenfield-service: nascente-servico
    greenfield-ui: nascente-interface
    brownfield-fullstack: existente-completo
    brownfield-service: existente-servico
    brownfield-ui: existente-interface

# ===================================
# MAPEAMENTO DE TEMPLATES
# ===================================
templates:
  categorias:
    requirements: requisitos
    architecture: arquitetura
    design: design
    testing: teste
    documentation: documentacao

  tipos:
    prd: prd
    story: historia
    epic: epico
    task: tarefa
    bug: bug
    feature: funcionalidade
    architecture: arquitetura
    test-plan: plano-teste

  nomes_completos:
    prd-template: modelo-prd
    user-story-template: modelo-historia-usuario
    epic-template: modelo-epico
    architecture-template: modelo-arquitetura
    test-plan-template: modelo-plano-teste

# ===================================
# TERMOS TÉCNICOS (não traduzir)
# ===================================
termos_tecnicos:
  preservar:
    - API
    - REST
    - GraphQL
    - JSON
    - YAML
    - SQL
    - NoSQL
    - CI/CD
    - Docker
    - Kubernetes
    - Git
    - GitHub
    - React
    - Vue
    - Angular
    - Node
    - Python
    - Java
    - JavaScript
    - TypeScript
    - HTML
    - CSS
    - SASS
    - OAuth
    - JWT
    - CORS
    - HTTP
    - HTTPS
    - WebSocket
    - Redux
    - MVC
    - MVVM
    - MVP
    - SOLID
    - DRY
    - KISS
    - YAGNI
    - TDD
    - BDD
    - DDD

# ===================================
# MENSAGENS E RESPOSTAS
# ===================================
mensagens:
  saudacoes:
    hello: olá
    hi: oi
    welcome: bem-vindo
    goodbye: tchau
    bye: até logo
    thanks: obrigado
    thank you: muito obrigado

  confirmacoes:
    yes: sim
    no: não
    ok: ok
    confirm: confirmar
    cancel: cancelar
    continue: continuar
    abort: abortar

  status:
    success: sucesso
    error: erro
    warning: aviso
    info: informação
    loading: carregando
    processing: processando
    complete: completo
    incomplete: incompleto
    pending: pendente
    failed: falhou

# ===================================
# REGRAS ESPECIAIS DE TRADUÇÃO
# ===================================
regras_especiais:
  # Manter capitalização em nomes próprios
  manter_capitalizacao:
    - BMAD
    - PRISMA
    - Claude
    - Anthropic

  # Contextos que mudam tradução
  contexto_sensivel:
    - pattern: "test"
      em_qa: "teste"
      em_dev: "testar"
    - pattern: "build"
      em_ci: "construir"
      em_dev: "compilar"

  # Composições especiais
  composicoes:
    "drag and drop": "arrastar e soltar"
    "copy and paste": "copiar e colar"
    "plug and play": "conectar e usar"
    "click through": "clicar através"

# ===================================
# CONFIGURAÇÕES DO ADAPTADOR
# ===================================
adaptador:
  # Cache de traduções
  cache:
    habilitado: true
    ttl_segundos: 300
    tamanho_maximo: 1000

  # Performance
  performance:
    timeout_ms: 100
    tentativas: 3
    circuit_breaker: true

  # Logging
  logging:
    nivel: info
    arquivo: logs/adaptador.log
    rotacao: diaria

  # Fallback
  fallback:
    modo: bmad
    alertar: true
    tentar_corrigir: true

# ===================================
# MÉTRICAS E MONITORAMENTO
# ===================================
metricas:
  rastrear:
    - total_traducoes
    - taxa_cache_hit
    - latencia_media
    - erros_traducao
    - comandos_desconhecidos
    - uso_por_agente
    - migracao_progresso