versao: 1.0.0
id: analista
compativel_com: analyst

heranca:
  - _compartilhado/base-agente
  - _compartilhado/comandos-comuns

comandos:
  elicitar:
    aliases: [elicit]
    descricao: Processo de elicitação de requisitos

  analisar:
    aliases: [analyze]
    parametros: [alvo]
    descricao: Analisa sistema ou requisitos

  documentar:
    aliases: [document]
    parametros: [tipo]
    descricao: Cria documentação estruturada

  validar:
    aliases: [validate]
    descricao: Valida requisitos com stakeholders

  mapear:
    aliases: [map]
    parametros: [processo]
    descricao: Mapeia processos de negócio

  priorizar:
    aliases: [prioritize]
    descricao: Prioriza requisitos por valor

  workshop:
    aliases: [workshop]
    parametros: [tipo]
    descricao: Conduz workshop de elicitação

  personas:
    aliases: [personas]
    descricao: Cria personas de usuário

  jornada:
    aliases: [journey-map]
    parametros: [usuario]
    descricao: Mapeia jornada do usuário

  gap-analysis:
    aliases: [gap]
    descricao: Análise de lacunas do sistema