# Configuração do Orquestrador PRISMA
versao: 1.0.0
id: orquestrador
compativel_com: bmad-orchestrator

# Herança de componentes base
heranca:
  - _compartilhado/base-agente
  - _compartilhado/comandos-comuns
  - _compartilhado/validadores

# Componentes específicos do orquestrador
componentes:
  roteamento: componentes/roteamento.md
  descoberta: componentes/descoberta.md
  recomendador: componentes/recomendador.md
  transformacao: componentes/transformacao.md

# Comandos disponíveis
comandos:
  # Comandos principais
  ajuda:
    aliases: [help, h, "?"]
    descricao: Mostra guia de comandos

  agente:
    aliases: [agent, a]
    parametros: [nome]
    descricao: Transforma em agente especializado

  tarefa:
    aliases: [task, t]
    parametros: [nome, opcoes?]
    descricao: Executa tarefa específica

  fluxo:
    aliases: [workflow, w, flow]
    parametros: [tipo]
    descricao: Inicia workflow completo

  estado:
    aliases: [status, s]
    flags: [--detalhado, --resumo]
    descricao: Mostra contexto atual

  sair:
    aliases: [exit, quit, q]
    descricao: Retorna ao modo anterior

  # Modos especiais
  modo-chat:
    aliases: [chat-mode, chat]
    descricao: Modo conversacional detalhado

  modo-kb:
    aliases: [kb-mode, kb]
    descricao: Base de conhecimento

  modo-festa:
    aliases: [party-mode, party]
    descricao: Todos agentes ativos

  modo-yolo:
    aliases: [yolo]
    descricao: Sem confirmações

  # Comandos de listagem
  listar:
    aliases: [list, ls, l]
    parametros: [tipo]
    opcoes:
      - agentes
      - tarefas
      - fluxos
      - templates
    descricao: Lista recursos disponíveis

# Agentes gerenciados
agentes_disponiveis:
  - id: analista
    bmad_id: analyst
    descricao: Análise de requisitos

  - id: arquiteto
    bmad_id: architect
    descricao: Arquitetura de soluções

  - id: desenvolvedor
    bmad_id: dev
    descricao: Implementação e código

  - id: gerente-projeto
    bmad_id: pm
    descricao: Gestão de projeto

  - id: product-owner
    bmad_id: po
    descricao: Visão de produto

  - id: qualidade
    bmad_id: qa
    descricao: Testes e validação

  - id: scrum-master
    bmad_id: sm
    descricao: Facilitação ágil

  - id: especialista-ux
    bmad_id: ux-expert
    descricao: Design e usabilidade

# Workflows disponíveis
workflows:
  nascente:
    - nascente-completo
    - nascente-servico
    - nascente-interface

  existente:
    - existente-completo
    - existente-servico
    - existente-interface

  hibrido:
    - hibrido-migracao
    - hibrido-integracao

# Detecção inteligente
deteccao:
  padroes:
    - pattern: "(bug|erro|problema|issue)"
      sugestao: agente desenvolvedor
      comando: debug

    - pattern: "(api|backend|servico|endpoint)"
      sugestao: fluxo nascente-servico

    - pattern: "(tela|interface|frontend|ui|ux)"
      sugestao: agente especialista-ux

    - pattern: "(teste|validar|qa|qualidade)"
      sugestao: agente qualidade

    - pattern: "(requisito|documento|analise)"
      sugestao: agente analista

    - pattern: "(arquitetura|design|diagrama)"
      sugestao: agente arquiteto

# Configurações de comportamento
comportamento:
  saudacao_inicial: |
    🎭 Orquestrador PRISMA Ativado!
    Sistema bilíngue BMAD/PRISMA funcionando
    Digite 'ajuda' para ver comandos disponíveis

  sugestoes_automaticas: true
  verbosidade: normal
  confirmacoes: true
  preservar_contexto: true
  timeout_sessao: 1800  # 30 minutos

# Métricas e monitoramento
metricas:
  coletar: true
  eventos:
    - comando_executado
    - agente_transformado
    - workflow_iniciado
    - erro_detectado
    - sugestao_aceita

# Cache e performance
cache:
  habilitado: true
  ttl: 300
  tamanho_maximo: 100