# PRISMA - Configuração Central do Sistema
# Meta-Agente para Claude Code com Subagentes Especializados

system:
  name: "PRISMA"
  version: "1.0.0"
  description: "Meta-agente para orquestração de subagentes Claude Code"

agents:
  max_concurrent: 3
  default_model: "sonnet"
  timeout: 300
  retry_attempts: 2

registry:
  auto_discovery: true
  agents_path: ".prisma/agents/"
  workflows_path: ".prisma/workflows/"

logging:
  level: "info"
  path: ".prisma/logs/"
  event_sourcing: true

state:
  persistence: true
  path: ".prisma/state/"
  cache_ttl: 3600

workflows:
  default_chain: ["state-manager", "context-analyzer", "progress-tracker"]

core_agents:
  - name: "state-manager"
    priority: 1
    description: "Gerencia persistência e estado dos agentes"
  - name: "event-logger"
    priority: 2
    description: "Event sourcing e auditoria"
  - name: "context-analyzer"
    priority: 3
    description: "Análise e cache de contexto"
  - name: "progress-tracker"
    priority: 4
    description: "Tracking e visualização de progresso"